name: Staging DAG Deployment
on:
  push:
    branches:
      - staging
      - dev-int

jobs:
  dag_deployment:
    name: DAG Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.G_TOKEN }}
          
  #    - name: DAG image creation and airflow deployment
  #      uses: elgohr/Publish-Docker-Github-Action@master
  #      with:
  #        name: ${{ secrets.STG_RELEASE_NAME }}/airflow:deploy-ci-${{ github.run_number }}
  #        username: _
  #        password: ${{ secrets.SA_PASS_KEY }}
  #        registry: registry.astronomer.condenast.io
          
  branch_creation:
    runs-on: ubuntu-latest
    environment: 'prod-branch-creation'
    needs: dag_deployment
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.G_TOKEN }}
          fetch-depth: 0

      - name: tag creation
        run: |
          version_increament=0.1
          current_tag=`git tag --sort version:refname | tail -n1`
          echo "$current_tag + $version_increament" | bc > ./vertion_tag.txt
          cat ./version_tag.txt
          echo "::set-output name=tag_version::$(cat ./vertion_tag.txt)"
          rm -rf ./vertion_tag.txt
      #- name: Tag Creation
      #  id: tag_version
      #  run: |
      #    chmod +x ./scripts/tag_creation.sh
      #    sh scripts/tag_creation.sh

      #- name: tagging
      #  uses: rickstaa/action-create-tag@v1
      #  with:
      #    tag: ${{ steps.tag_version.outputs.TAG_NAME }}
      #    message: "latest tag created"

      #- name: Production branch creation
        #run: |
          #git branch
          #git checkout -b production $vertion_tag
          #git push origin production